services:
  atm:
    build: .
    restart: unless-stopped
    environment:
      XMS: 4G
      XMX: 8G
      MAX_AGE_BACKUP_FILES: 30d
      PRE_START_BACKUP: "false"
      POST_START_BACKUP: "false"
    ports:
      - "25823:25565"
    volumes:
      - './minecraft-data:/data'
